# version: '3'
services:
  web:
    container_name: umpire-run
    image: em492028/umpire-run:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next